/*
 Проект существующий сейчас который переезжает на рельсы postgres.
Итак.
БД hives это пул основаный по территориальному признаку.
БД nodes это нода на которой крутится прокси.
БД operators это информация об мобильном операторе.
Это пул мобильных проксей, разных операторов, который размещен территориально.
Есть тщвуы, назовем их bee101,bee102 итд (на деле это одноплатные компьютеры OrangePi с модемами 4G).
Есть так назывемые соты Hive, в каждой соте есть свой пул nodes.
heve100 относятся прокси bee101, bee102 и тд.
heve200 относятся прокси bee201, bee202 и тд.
 */

create table hives (
       id integer generated by default as identity,
       name varchar(50) not null,
       created_at timestamp default current_timestamp,
       updated_at timestamp,

       constraint hives_id_pkey primary key (id)
);

create table nodes (
       id integer generated by default as identity,
       hive_id integer not null,
       hostname varchar (50) not null,
       address varchar (50) not null,
       created_at timestamp default current_timestamp,
       updated_at timestamp,
	
       constraint nodes_id_pkey primary key (id),
       constraint nodes_hostname_key unique (hostname),
       constraint nodes_hive_id_fkey foreign key (hive_id) references hives(id) on delete restrict
);


create table operators (
       id integer generated by default as identity,
       node_id integer not null,
       operator varchar(50) not null,
       phone varchar(50) not null,
       created_at timestamp default current_timestamp,
       updated_at timestamp,

       constraint operators_id_pkey primary key (id),
       constraint operators_node_id_fkey foreign key (node_id) references nodes(id) on delete cascade
);

insert into hives (name) values
        ('heve100'),
        ('heve200'),
        ('heve300'),
        ('heve400');

insert into nodes (hive_id, hostname, address) values
	(1, 'bee101', '1.1.1.1:7011'),
	(1, 'bee102', '1.1.1.1:7012'),
	(1, 'bee103', '1.1.1.1:7013'),
	(1, 'bee104', '1.1.1.1:7014'),
	(1, 'bee105', '1.1.1.1:7015'),
	(2, 'bee201', '2.2.2.2:7021'),
        (2, 'bee202', '2.2.2.2:7022'),
        (2, 'bee203', '2.2.2.2:7023'),
        (2, 'bee204', '2.2.2.2:7024'),
        (2, 'bee205', '2.2.2.2:7025'),
	(3, 'bee301', '3.3.3.3:7031'),
        (3, 'bee302', '3.3.3.3:7032'),
        (3, 'bee303', '3.3.3.3:7033'),
        (3, 'bee304', '3.3.3.3:7034'),
        (3, 'bee305', '3.3.3.3:7035'),
	(4, 'bee401', '4.4.4.4:7041'),
        (4, 'bee402', '4.4.4.4:7042'),
        (4, 'bee403', '4.4.4.4:7043'),
        (4, 'bee404', '4.4.4.4:7044'),
        (4, 'bee405', '4.4.4.4:7045');


insert into operators (node_id, operator, phone) values
	(1, 'Beeline', '+7(965)284-13-74'),
	(2, 'MTS', '+7(965)284-13-74'),
	(3, 'Yota', '+7(965)284-13-74'),
	(4, 'Megafon', '+7(965)284-13-74'),
	(5, 'Tele2', '+7(965)284-13-74'),
	(6, 'Beeline', '+7(965)284-13-74'),
	(7, 'Megafon', '+7(965)284-13-74'),
	(8, 'Mts', '+7(965)284-13-74'),
	(9, 'Yota', '+7(965)284-13-74'),
	(10, 'Beeline', '+7(965)284-13-74'),
	(11, 'Beeline', '+7(965)284-13-74'),
        (12, 'MTS', '+7(965)284-13-74'),
        (13, 'Yota', '+7(965)284-13-74'),
        (14, 'Megafon', '+7(965)284-13-74'),
        (15, 'Tele2', '+7(965)284-13-74'),
        (16, 'Beeline', '+7(965)284-13-74'),
        (17, 'Megafon', '+7(965)284-13-74'),
        (18, 'Mts', '+7(965)284-13-74'),
        (19, 'Yota', '+7(965)284-13-74'),
        (20, 'Beeline', '+7(965)284-13-74');


/* 
 продолжение следует.......
 */
